// Strings
const APP_NAME = 'StarWars';

const LOGIN_EMAIL_TEXTFIELD_HINT_TEXT = 'E-MAIL';
const LOGIN_PASSWORD_TEXTFIELD_HINT_TEXT = 'SENHA';
const LOGIN_FORGOT_PASSWORD_GESTURE_TEXT = 'ESQUECEU A SENHA?';
const LOGIN_BUTTON_TEXT = 'LOGIN';
const LOGIN_REGISTER_GESTURE_TEXT_REGULAR = 'Não possui cadastro?';
const LOGIN_REGISTER_GESTURE_TEXT_BOLD = 'Clique aqui';

const SIGNUP_PAGE_TITLE = 'Cadastro';
const SIGNUP_PAGE_SUBTITLE_1 = 'INFORME SEUS DADOS PARA CADASTRO';
const SIGNUP_PAGE_SUBTITLE_2 = 'CADASTRE UMA SENHA';
const SIGNUP_NAME_TEXTFIELD_HINT_TEXT = 'NOME';
const SIGNUP_BIRTH_TEXTFIELD_HINT_TEXT = 'NASCIMENTO';
const SIGNUP_EMAIL_TEXTFIELD_HINT_TEXT = 'E-MAIL';
const SIGNUP_PASSWORD_TEXTFIELD_HINT_TEXT = 'SENHA';
const SIGNUP_CONFIRM_PASSWORD_TEXTFIELD_HINT_TEXT = 'CONFIRMAR SENHA';
const SIGNUP_BUTTON_TEXT_1 = 'PRÓXIMO';
const SIGNUP_BUTTON_TEXT_2 = 'CONFIRMAR';

const FORGOT_PASSWORD_PAGE_TITLE = 'ESQUECI A SENHA';
const FORGOT_PASSWORD_PAGE_SUBTITLE_1 = 'DIGITE SEU E-MAIL';
const FORGOT_PASSWORD_PAGE_SUBTITLE_2 = 'DIGITE O CÓDIGO';
const FORGOT_PASSWORD_PAGE_SUBTITLE_3 = 'DIGITE SUA NOVA SENHA E CONFIRME!';
const FORGOT_PASSWORD_EXPLANATION_1 =
    'Enviaremos um e-mail com um código para a alteração de sua senha';
const FORGOT_PASSWORD_EXPLANATION_2 =
    'Para continuar, você deverá informar o código recebido para o e-mail ';
const FORGOT_PASSWORD_EMAIL_TEXTFIELD_HINT_TEXT = 'E-MAIL';
const FORGOT_PASSWORD_RESETCODE_TEXTFIELD_HINT_TEXT = 'INSIRA O CÓDIGO';
const FORGOT_PASSWORD_PASSWORD_TEXTFIELD_HINT_TEXT = 'SENHA';
const FORGOT_PASSWORD_CONFIRM_PASSWORD_TEXTFIELD_HINT_TEXT = 'CONFIRMAR SENHA';
const FORGOT_PASSWORD_RESET_CODE_GESTURE_TEXT = 'REENVIAR CÓDIGO';
const FORGOT_PASSWORD_BUTTON_TEXT_1 = 'ENVIAR';
const FORGOT_PASSWORD_BUTTON_TEXT_2 = 'PRÓXIMO';

const CHOOSE_SIDE_SUBTITLE = 'Escolha o seu lado da força';
const CHOOSE_SIDE_TEXT = 'SELECIONAR';

const INTERNAL_SERVER_ERROR_MESSAGE = 'Server Error';
const ERROR_TAP_VALID_EMAIL = 'DIGITE UM E-MAIL VÁLIDO';
const ERROR_EMAIL_NOT_FOUND = 'E-MAIL NÃO ENCONTRADO';
const ERROR_INCORRECT_PASSWORD = 'SENHA INCORRETA';
const ERROR_EMAIL_ALREADY_EXISTS = 'E-MAIL JÁ CADASTRADO';
const ERROR_PASSWORDS_MUST_BE_EQUAL = 'AS SENHAS DEVEM SER IGUAIS';
const ERROR_PASSWORD_TOO_SMALL = 'SENHA COM NO MÍNIMO 6 CARACTERES';
